name: example-environment
resources:
          requests:
            cpu: "12"
            memory: "30Gi"
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - pandas_ml
  - pip
  - keras
  - pillow
